-- --------------------------------------------------------
-- Servidor:                     localhost
-- Versão do servidor:           5.7.24 - MySQL Community Server (GPL)
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Copiando estrutura do banco de dados para blogautosports
DROP DATABASE IF EXISTS `blogautosports`;
CREATE DATABASE IF NOT EXISTS `blogautosports` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `blogautosports`;

-- Copiando estrutura para tabela blogautosports.postagens
CREATE TABLE IF NOT EXISTS `postagens` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titulo` varchar(250) NOT NULL,
  `descricao` varchar(250) NOT NULL,
  `categoria` varchar(250) DEFAULT NULL,
  `noticia` text,
  `data_post` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela blogautosports.postagens: ~18 rows (aproximadamente)
/*!40000 ALTER TABLE `postagens` DISABLE KEYS */;
INSERT INTO `postagens` (`id`, `titulo`, `descricao`, `categoria`, `noticia`, `data_post`) VALUES
	(6, 'Planos Para GP Da Áustria São Aprovados Pelo Governo E F1 Fica Próxima De Iniciar Temporada Em Julho', 'A F1 Deu O Passo Mais Importante Até O Momento Para O Início Da Temporada, Ao Receber Apoio Do Governo Austríaco Para Realizar As Provas', 'Formula 1', 'Após Semanas De Discussões Entre A Fórmula 1, A Direção Do Red Bull Ring E O Governo Austríaco, O Plano De Segurança Apresentado Para Viabilizar A Realização De Duas Etapas No Circuito Em Meio à Pandemia Foi Aprovado. Com Isso, A F1 Deu Seu Passo Mais Importante Até O Momento Para Garantir O Início Do Campeonato Em Julho.&#13;&#10;&#13;&#10;Essa Semana, O Ministro Da Saúde Rudi Anschober Já Havia Afirmado Que O Governo Havia Concluído A Avaliação Do Projeto. Porém, Iria Aguardar Mais Alguns Dias Antes Do Anúncio Da Decisão.', '2020-05-30 21:35:03'),
	(7, 'Renault Confirma Permanência Na F1 Apesar De Grave Crise Econômica', 'A Montadora Anunciou Que Continua Comprometida Com O Programa Da F1 Pelos Próximos Anos, Impulsionado Pelo Novo Teto Orçamentário', 'Formula 1', 'Há Algum Tempo, Já Haviam Dúvidas Sobre A Presença Da Renault Na Fórmula 1 Nos Próximos Anos, E A Crise Econômica Causada Pela Pandemia Da Covid-19 Aumentou Ainda Mais Essas Interrogações, Devido Ao Impacto Sofrido Pela Montadora. Porém, A CEO Interina Da Renault Confirmou A Permanência Da Empresa Na Categoria Para Os Próximos Anos.&#13;&#10;&#13;&#10;A Renault Foi Atingida Em Cheio Pela Crise Causada Pela Pandemia, E Anunciou Corte De 15 Mil Postos De Trabalho Ao Redor Do Mundo, Como Parte De Um Esforço Para Economizar Dois Bilhões De Euros (R$ 12 Bilhões) Nos Próximos Três Anos.', '2020-05-30 21:35:21'),
	(8, 'Mercedes Tem &#34;intenção Clara&#34; De Continuar Na F1 E Com Toto Wolff Ao Lado', 'A Equipe Alemã Deixou Claro Que Pretende Continuar Na F1 Como Uma Equipe De Fábrica, Sob A Direção De Toto Wolff', 'Formula 1', 'Nas últimas Semanas, Começaram A Surgir Rumores De Que A Mercedes Poderia Reduzir Seu Envolvimento Com A Fórmula 1, Ao Vender Parte Das Ações De Sua Divisão Esportiva Para A Aston Martin. Mas A Equipe Fez Questão De Deixar Claro Que Continua Comprometida Em Estar Presente Na F1 Como Uma Equipe De Fábrica E Com Um Detalhe Importante: Sob A Liderança De Toto Wolff.&#13;&#10;&#13;&#10;A Equipe, Que Venceu Os últimos Seis Mundiais De Construtores, Tem Contrato Para Correr Na F1 Até O Final De 2020, Mas Notícias Veiculadas Recentemente Sugeriam Que A Montadora Poderia Estar Prestes A Diminuir Seu Envolvimento Com O Campeonato, E A Aston Martin E Lawrence Stroll Poderiam Ter Papeis Fundamentais Nisso.', '2020-05-30 21:35:38'),
	(9, 'Racing Point Acredita Que Nova F1 Não Terá Espaço Para Equipes Grandes: &#34;Eles Terão Que Dar Um Passo Para Trás&#34;', 'Andrew Green, Da Racing Point, Afirmou Que As Equipes Grandes Terão Que Se Adaptar à Uma Realidade Que As Rivais Já Estão Acostumadas', 'Formula 1', 'Em 2021, A Fórmula 1 Terá Um Novo Teto Orçamentário, Que Limitará Os Gastos Da Equipes Em Determinadas áreas Em 145 Milhões De Dólares Por Temporada, Como Forma De Tornar A Competição Mais Sustentável. Isso, Porém, Deve Mexer Bastante Com Algumas Equipes Do Grid, Que Possuem Grandes Quadros De Funcionários. Esse Tipo De Equipe, Porém, Deve Estar Com Os Dias Contados, Segundo A Racing Point.&#13;&#10;&#13;&#10;Porém, Também Deve Causar A Demissão De Funcionários Das Maiores Equipes. Essa Semana, A McLaren Confirmou Que Irá Cortar 70 Vagas Do Departamento De F1 Como Parte De Cortes Maiores Dentro Da Empresa.', '2020-05-30 21:35:48'),
	(10, 'Elliott Se Redime E Consegue Vitória Em Charlotte', 'Piloto Que Esteve Perto De Triunfo No Domingo, Na Prova De 600 Milhas, Conseguiu Concretizar Vitória Na Corrida De 500 Km', 'Nascar', 'A NASCAR Cup Series Realizou Nesta Quinta-feira (28) A Segunda Corrida Em Charlotte, Carolina Do Norte, A Quarta Depois Da Volta Da Categoria Após A Paralisação Pelo Coronavírus. A Corrida De 500 Km Era Para Ter Sido Realizada Na Quarta, Mas A Chuva Acabou Obrigando Os Organizadores A Adiar O Evento.&#13;&#10;&#13;&#10;Mesmo Com Raios E A Chuva Novamente Atrapalhando O Início, A Prova Ocorreu Em Sua Totalidade E, Desta Vez, Nada Parou Chase Elliott. O Piloto Da Hendrick Motorsports, Que Perdeu A Corrida De Domingo Por Conta De Um Erro Estratégico, Após O Surgimento De Uma Bandeira Amarela Faltando Duas Voltas, Mostrou Força Novamente, E Conseguiu Triunfar Sem Grandes Sustos.', '2020-05-30 21:35:59'),
	(11, 'Mônaco Anuncia Planos Para Provas Da F1 E F-E Em 2021', 'Mônaco Pretende Realizar Três Provas Em 2021 Em Um Período De Cinco Semanas: O GP Histórico, O EPrix Da F-E E O GP De F1', 'Formula E', 'Após Ter Que Cancelar O GP Histórico E A Prova Da Fórmula 1 Desse Ano Como Resultado Da Pandemia Da Covid-19, O Automóvel Clube De Mônaco Se Mexeu Rapidamente Para Delimitar Os Planos Do Próximo Ano, Que Contará Com Uma Programação Inédita.&#13;&#10;&#13;&#10;Até Esse Ano, Mônaco Alternava A Realização Do GP Histórico E A Etapa Da Fórmula E, Com As Provas Acontecendo De Modo Bianual. Mas Agora O Clube Irá Realizar Os Três Eventos No Ano Que Vem, Em Um Período De Cinco Semanas.', '2020-05-30 21:38:08'),
	(12, 'Indy Divulga Novo Calendário Para 2020 Sem Etapa De Richmond', 'Etapa De Ontário Deve Ficar De Fora E Road America Terá Rodada Dupla Em Julho', 'IndyCar', 'Em Meio às Adaptações Na Temporada 2020 Por Causa Da Pandemia Do Novo Coronavírus, A IndyCar Divulgou Nesta Quinta-feira Um Novo Calendário Para Este Ano E Retirou A Etapa De Richmond Do Campeonato.&#13;&#10;&#13;&#10;A Decisão Sobre O Oval Se Deve Ao Fato De Que O Estado Da Virgínia Não Vai Permitir Aglomerações Pelo Menos Até Julho. Com Provas Acumuladas No Segundo Semestre, Richmond E A Indy Não Conseguiram Encontrar Uma Data Conveniente.', '2020-05-30 21:38:29'),
	(13, 'Chefe De Equipe Da Stock Car Explica Custos De Se Colocar Um Carro No Grid', 'Duda Pamplona, Chefe Da Crown Racing Com A Equipe Shell, Explicou Como Funciona O Lado Financeiro Da Stock Em Live Com O Motorsport.com', 'Stock Car', 'Correr Na Stock Car, A Categoria Mais Importante Do Automobilismo Nacional Requer Uma Quantidade De Dinheiro Que Condiz Com A Importância Do Campeonato. Mas Você Sabe Quanto Custa Participar De Uma Temporada Completa Da Stock?&#13;&#10;&#13;&#10;Duda Pamplona, Chefe Da Crown Racing Com A Equipe Shell Falou Sobre Os Valores Necessários Para Correr Com A Stock Car Durante A Live Feita Com O Motorsport.com, E Afirmou Que As Equipes Estão Buscando Reduzir Os Custos Para Os Próximos Anos, Prevendo O Impacto Econômico Da Pandemia Da Covid-19.', '2020-05-30 21:39:40'),
	(14, 'Hamilton Critica Violência Policial Após Morte De George Floyd: &#34;Vocês São Uma Desgraça&#34;', 'O Hexacampeão Usou Seu Perfil No Instagram Para Criticar As Ações Policiais Contra A População Negra Nos Estaods Unidos', 'Formula 1', 'O Hexacampeão Lewis Hamilton Sempre Usou Suas Redes Sociais Para Mostrar Coisas Além De Sua Vida Na Fórmula 1, Incluindo Opiniões Sobre Temas Como Mudanças Climáticas, A Dieta Vegana E O Racismo. Nesta Semana, Hamilton Voltou A Se Manifestar, Desta Vez Sobre A Morte Do Americano George Floyd.&#13;&#10;&#13;&#10;Floyd Foi Morto Por Um Policial Na Cidade De Minneapolis, No Estado Do Minnesota, Sob A Acusação De Tentar Pagar Suas Compras Com Uma Nota Falsa De 20 Dólares. Quatro Policiais Tentaram Conter Floyd E Um Deles, Derek Chauvin, Ficou Ajoelhado No Pescoço Do Homem De 46 Anos Por Cerca De Oito Minutos.', '2020-05-30 21:40:07'),
	(15, 'Corrida Do Milhão Da Stock Car Pode Ter Prêmio Voltado A Instituições De Combate Ao Coronavírus', 'Em Entrevista Exclusiva, Carlos Col Admitiu Dificuldades Em Arrecadar O Valor Da Premiação De Uma Das Principais Corridas Do Automobilismo Brasileiro', 'Stock Car', 'Um Dos Pontos Altos Da Categoria, A Corrida Do Milhão, Está Marcada Para Acontecer No Dia 23 De Agosto, Em Interlagos. Durante Entrevista Exclusiva Ao Motorsport.com Em Live No Instagram, Carlos Col, CEO Da Vicar, Empresa Que Organiza A Stock Car, Admitiu Ter Dificuldades Em Conseguir Patrocínios Para Ter A Premiação De R$ 1 Milhão, Mas Que Vê Com Bons Olhos Uma Mudança Na Maneira De Oferecer O Milhão.&#13;&#10;&#13;&#10;“A Corrida Do Milhão Está Confirmada”, Disse Col. “Como Esse Milhão Será Pago, Eu Ainda Não Sei, Mas Vamos Encontrar Uma Maneira. A Corrida Do Milhão é Um Marco, Vou Fazer Todo O Esforço Possível Para Mantê-la, Estou Abrindo Aqui Com Muita Sinceridade Das Dificuldades Financeiras óbvias Deste Ano, Um Patrocinador Ainda Precisa Ser Conquistado, Vamos Discutir Isso Com Pilotos E Equipes, Nem Que A Gente Tenha Que Fazer Um Carnezinho Para Pagar.”&#13;&#10;&#13;&#10;“Quem Sabe, Não Discuti Ainda, Vou Falar Aqui Em Primeira Mão, Da Gente Transformar Essa Premiação Em Uma Doação Em Prol Ao Combate Ao Coronavírus, Para Beneficiar Quem Estiver Atuando De Maneira Transparente.”&#13;&#10;&#13;&#10; “Tenho Certeza De Que Quando Eu Apresentar Essa Ideia, Teremos A Adesão De Todos. Talvez Até Possamos Ter Esse Milhão Em Produtos, Como Cestas Básicas, Máscaras, álcool Gel, Medicamentos E Talvez Isso Até Facilite Eu Fazer Essa Captação Deste Milhão.”', '2020-05-30 23:49:20'),
	(16, 'Stock Car Planeja 12 Etapas Em Oito Fins De Semana Com Corridas Aos Sábados', 'Maior Categoria Do Automobilismo Brasileiro Remanejará As Quatro Primeiras Etapas Em Corridas Realizadas Aos Sábados', 'Stock Car', 'A Crise Do Coronavírus Mudou De Vez A Cara Do Automobilismo Brasileiro E Mundial. A Stock Car, Maior E Mais Tradicional Categoria Do Brasil, Também Foi Afetada Pela Pandemia, Se Vendo Obrigada A Suspender As Primeiras Quatro Etapas Do Ano, Sendo Uma Delas A Corrida De Duplas, Que Abriria O Campeonato, Em Goiânia, No Final De Março.&#13;&#10;&#13;&#10;Nesta Segunda-feira, Carlos Col, CEO Da Vicar, Anunciou As Modificações Do Calendário Com Algumas Novidades Em Entrevista Ao Globoesporte.com E Confirmadas Pelo Motorsport.com. O Campeonato Começa No Fim De Semana De 28 De Junho, No Velo Città E Seguirá O Calendário Previamente Anunciado No Final Do Ano Passado.', '2020-05-30 23:50:13'),
	(17, 'Chefe Da Stock Car Negocia Volta De Curitiba Para Temporada 2020', 'Em Entrevista Exclusiva Ao Motorsport.com, Carlos Col Detalhou Como Poderá Ser O Campeonato Deste Ano', 'Stock Car', 'A Crise Do Novo Coronavírus Mudou Radicalmente A Temporada 2020 Da Stock Car. Neste Ano, A Principal Categoria Brasileira Volta A Ser Multimarca, Com A Entrada Da Toyota Em Oito Carros Do Grid, Além Do Novo Modelo Adotado Pela Chevrolet.&#13;&#10;&#13;&#10;Quanto Ao Calendário, A Solução Foi Colocar As Quatro Primeiras Etapas ‘perdidas’ Por Causa Da Covid-19 Nos Oito Fins De Semana Restantes, Mantendo As Datas Previamente Agendadas, Mas Com Corridas Aos Sábados Em Um Formado Semelhante à Corrida Do Milhão.', '2020-05-30 23:50:54'),
	(18, 'Vergne Diz Que Sonha Com Fusão Entre Fórmula 1 E Fórmula E No Futuro', 'Francês Acredita Que Uma Combinação De Fórmula 1 E Fórmula E Pode Ser O Futuro Do Automobilismo', 'Formula E', 'Com Todo O Esporte A Motor Em Espera Durante A Pandemia De Coronavírus, Cada Categoria Tem Planejado A Melhor Forma De Retomar As Corridas, Quando Receberem A Luz Verde Das Autoridades De Saúde.&#13;&#10;&#13;&#10;Enquanto A Fórmula E Está No Meio Da Temporada 2019-2020, A F1 Quase Iniciou A Temporada Com O GP Da Austrália, Cancelado Horas Antes Do Início Dos Treinos De Sexta-feira, Depois Que Um Membro Da McLaren Testou Positivo Para A Covid-19.', '2020-05-30 23:52:00'),
	(19, 'Di Grassi Diz Que Próximo Carro Da F-E Pode Ser “tão Ou Mais Rápido” Que F1 Atual', 'Brasileiro Vê Pressão Adicional Contra F1 Após Categoria De Carros Elétricos Conseguir Chegar Ao Mesmo Nível De Velocidade', 'Formula E', 'A Fórmula E Realiza A Sexta Temporada De Sua História, Utilizando A Segunda Geração De Seus Carros, Desde A Temporada Passada Com Um Modelo De Bateria Suficiente Para Uma Corrida Completa, Com A Troca De Carros Sem Necessidade De Acontecer.&#13;&#10;&#13;&#10;Mas Mais Do Que A Bateria, A Evolução Da Potência Dos Carros Da Fórmula E Também Vem Evoluindo. O Gen2 Evo Deve Entrar Em Ação Na Temporada 2021/2022, Com O Carro De Terceira Geração Nas Temporadas Seguintes.', '2020-05-30 23:52:51'),
	(20, 'Ferrari Confirma Que Avalia Projeto Na Indy A Partir De 2022', 'Limite Orçamentário Na F1 Poderá Abrir Portas Para Outros Programas De Fabricante Italiana, Como Indy', 'IndyCar', 'O Chefe Da Ferrari, Mattia Binotto, Admitiu Que A Fabricante Italiana Está Atualmente Investigando A Possibilidade De Entrar Na Indy, Possivelmente A Partir De 2022.&#13;&#10;&#13;&#10;Poucos Dias Após O ícone Mario Andretti Ter Pedido Que A Escuderia Considerasse A Entrada Na Categoria, Binotto Admitiu Que Tanto A Indy Quanto As Corridas De Carros Esportivos Estão Em Discussão Na Base De Maranello.', '2020-05-30 23:54:49'),
	(21, 'IndyCar Confirma Que Temporada 2020 Começará No Texas E Sem Fãs', 'Maior Categoria Norte-americana De Monopostos Terá Seu Campeonato Iniciado No Dia 6 De Junho', 'IndyCar', 'A IndyCar Confirmou Nesta Quinta-feira Que A Temporada 2020 Da Categoria Norte-americana De Monopostos Começará No Sábado, Dia 6 De Junho, Com A Etapa Do Texas Motor Speedway, De Portões Fechados.&#13;&#10;&#13;&#10;A Medida Foi Anunciada Como Precaução à Pandemia De Coronavírus E O Evento Será Condensado A Fim De Ser Concluído Mais Rapidamente. A Corrida, Portanto, Será Reduzida Para 200 Voltas No Oval De 2,4 Quilômetros Perto De Fort Worth.', '2020-05-30 23:55:24'),
	(22, 'Button, Alonso E Jimmie Johnson Podem Ocupar Terceiro Carro Da McLaren Na Indy', 'Zak Brown, CEO Da McLaren, Admitiu Que Jimmie Johnson E Jenson Button Estão Interessados Em Competir Em Carro Da McLaren, Enquanto Que Fernando Alonso Também Poderia Competir Em Outras Etapas Além Da Indy 500', 'IndyCar', 'Até Agora, Entre Fernando Alonso, Jenson Button E Jimmie Johnson, O único Com Vaga Confirmada Na Indy é O Bicampeão Mundial De Fórmula 1. O Espanhol De 38 Anos Pretende Fazer Sua Segunda Corrida De Indy 500 Em 2020.&#13;&#10;&#13;&#10;No Entanto, Antes Da Pandemia De Coronavírus Interromper As Corridas Nos Estados Unidos, O Motorsport.com Apurou Que Alonso Também Deveria Guiar Um Terceiro Carro Da McLaren SP - Ao Lado De Patricio O&#39;Ward E Oliver Askew - No GP De Indianápolis (circuito Misto). Acredita-se Que Esse Acordo Ainda Se Mantenha Firme, Embora, Em Vez De Eventos Consecutivos, O GP Está Marcado Para 4 De Julho, Enquanto Que A 104ª Edição Da Indy 500 Ocorrerá Em 23 De Agosto.', '2020-05-30 23:56:02'),
	(23, 'Harvick Conquista 50ª Vitória Na Volta Da NASCAR Após Paralisação Pela Pandemia', 'Um Dos Pilotos De Maior Experiência Do Grid Foi O Vitorioso Na Volta Da NASCAR Neste Domingo Em Darlington', 'Nascar', 'Kevin Harvick, Que Estava Na Liderança Do Campeonato Apesar De Ainda Não Ter Vencido Quando A NASCAR Suspendeu Sua Temporada, Corrigiu Esse Erro Com Uma Performance Dominante Em Darlington Nesse Domingo.&#13;&#10;&#13;&#10;O Piloto Liderou 159 Das 293 Voltas Da Corrida E Contou Com A Ajuda De Sua Equipe Que Fez Um Grande Trabalho Nas Paradas. Harvick Segurou Alex Bowman Por Pouco Mais De Dois Segundos, E Se Manteve Como O único Piloto A Terminar No Top 10 Em Todas As Provas Da Temporada.', '2020-05-30 23:57:05'),
	(24, 'NASCAR Anuncia Retorno Em 17 De Maio E Quatro Provas Da Cup Em 10 Dias', 'Maior Categoria Do Automobilismo Americano Anunciou Calendário Revisado De Maio, Com Quatro Provas Da Cup Em 10 Dias E Sem Presença De Público', 'Nascar', 'Para A Alegria Dos Fãs, A NASCAR Anunciou De Forma Oficial O Retorno De Suas Competições, Após Paralisação Por Conta Da Pandemia Do Coronavírus. As Etapas De Atlanta, Homestead-Miami, Texas, Richmond, Talladega E Martinsville Tiveram Que Ser Suspensas Por Causa Do Covid-19.&#13;&#10;&#13;&#10;O Retorno Acontecerá No Dia 17 De Maio, Dando Início A Uma Sequência De Quatro Corridas Da Cup Em 10 Dias, Mas Apenas Em Darlington E Charlotte.', '2020-05-30 23:58:33');
/*!40000 ALTER TABLE `postagens` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
